"use client";

import { useState } from "react";
import { Button, Input } from "@zmzai/theme";
import { cnyYuanToMicros } from "@/providers/billing/currency";

export function OperationsPanel() {
  const [message, setMessage] = useState<string | null>(null);
  async function price(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const res = await fetch("/api/admin/prices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model: form.get("model"), inputPricePer1kMicros: cnyYuanToMicros(Number(form.get("input"))), outputPricePer1kMicros: cnyYuanToMicros(Number(form.get("output"))), cacheReadPricePer1kMicros: cnyYuanToMicros(Number(form.get("cacheRead") || 0)), cacheWritePricePer1kMicros: cnyYuanToMicros(Number(form.get("cacheWrite") || 0)), maxInputTokens: Number(form.get("maxInput")), maxOutputTokens: Number(form.get("maxOutput")), featured: form.get("featured") === "on", featuredDescription: form.get("featuredDescription") || "", enabled: true, reason: form.get("reason") }) }); setMessage(res.ok ? "价目已保存" : "价目保存失败"); }
  async function balance(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const res = await fetch("/api/admin/balances", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: form.get("userId"), amountMicros: cnyYuanToMicros(Number(form.get("amount"))), reason: form.get("reason") }) }); setMessage(res.ok ? "余额已调整" : "余额调整失败"); }
  return <div className="grid gap-8 lg:grid-cols-2"><form onSubmit={price} className="flex flex-col gap-3 border border-line bg-surface p-5"><h2 className="headline text-lg">公开价目</h2><Input name="model" required className="font-mono text-sm" placeholder="模型名，例如 gpt-5.6-terra"  /><div className="grid grid-cols-2 gap-3"><Input name="input" required type="number" min="0" step="0.0001" className="" placeholder="输入价格（元/1k）"  /><Input name="output" required type="number" min="0" step="0.0001" className="" placeholder="输出价格（元/1k）"  /></div><div className="grid grid-cols-2 gap-3"><Input name="cacheRead" type="number" min="0" step="0.0001" className="" placeholder="缓存读价格（元/1k）"  /><Input name="cacheWrite" type="number" min="0" step="0.0001" className="" placeholder="缓存写价格（元/1k）"  /></div><div className="grid grid-cols-2 gap-3"><Input name="maxInput" required type="number" min="1" defaultValue="16384" className=""  /><Input name="maxOutput" required type="number" min="1" defaultValue="4096" className=""  /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="featured" className="" /> 设为推荐模型</label><Input name="featuredDescription" className="" placeholder="推荐描述，例如：速度、质量和成本表现均衡的模型"  /><Input name="reason" required className="" placeholder="调价原因"  /><Button className="bg-accent text-accent-ink hover:bg-accent-strong self-start">保存价目</Button></form><form onSubmit={balance} className="flex flex-col gap-3 border border-line bg-surface p-5"><h2 className="headline text-lg">余额调整</h2><Input name="userId" required className="font-mono text-sm" placeholder="用户 Mongo ID"  /><Input name="amount" required type="number" step="0.01" className="" placeholder="金额（人民币元；负数为扣款）"  /><Input name="reason" required className="" placeholder="调整原因"  /><Button className="bg-accent text-accent-ink hover:bg-accent-strong self-start">调整余额</Button></form>{message ? <p className="font-mono text-sm text-accent-readable lg:col-span-2">{message}</p> : null}</div>;
}
