"use client";

import { useState } from "react";

export function OperationsPanel() {
  const [message, setMessage] = useState<string | null>(null);
  async function price(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const res = await fetch("/api/admin/prices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model: form.get("model"), inputPricePer1kMicros: Number(form.get("input")), outputPricePer1kMicros: Number(form.get("output")), maxInputTokens: Number(form.get("maxInput")), maxOutputTokens: Number(form.get("maxOutput")), enabled: true, reason: form.get("reason") }) }); setMessage(res.ok ? "价目已保存" : "价目保存失败"); }
  async function balance(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const res = await fetch("/api/admin/balances", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: form.get("userId"), amountMicros: Number(form.get("amount")), reason: form.get("reason") }) }); setMessage(res.ok ? "余额已调整" : "余额调整失败"); }
  return <div className="grid gap-8 lg:grid-cols-2"><form onSubmit={price} className="flex flex-col gap-3 border border-line bg-surface p-5"><h2 className="headline text-lg">公开价目</h2><input name="model" required className="border border-line bg-paper px-3 py-2 font-mono text-sm" placeholder="模型名，例如 gpt-5.6-terra" /><div className="grid grid-cols-2 gap-3"><input name="input" required type="number" min="0" className="border border-line bg-paper px-3 py-2" placeholder="输入微美元/1k" /><input name="output" required type="number" min="0" className="border border-line bg-paper px-3 py-2" placeholder="输出微美元/1k" /></div><div className="grid grid-cols-2 gap-3"><input name="maxInput" required type="number" min="1" defaultValue="16384" className="border border-line bg-paper px-3 py-2" /><input name="maxOutput" required type="number" min="1" defaultValue="4096" className="border border-line bg-paper px-3 py-2" /></div><input name="reason" required className="border border-line bg-paper px-3 py-2" placeholder="调价原因" /><button className="btn-primary self-start">保存价目</button></form><form onSubmit={balance} className="flex flex-col gap-3 border border-line bg-surface p-5"><h2 className="headline text-lg">余额调整</h2><input name="userId" required className="border border-line bg-paper px-3 py-2 font-mono text-sm" placeholder="用户 Mongo ID" /><input name="amount" required type="number" className="border border-line bg-paper px-3 py-2" placeholder="金额（微美元；负数为扣款）" /><input name="reason" required className="border border-line bg-paper px-3 py-2" placeholder="调整原因" /><button className="btn-primary self-start">调整余额</button></form>{message ? <p className="font-mono text-sm text-accent-readable lg:col-span-2">{message}</p> : null}</div>;
}
