"use client";

import { useState } from "react";

interface Key { _id: string; prefix: string; name: string; status: string; rateLimitPerMinute: number; monthlySpendLimitMicros: number; monthlySpendUsedMicros: number; lastUsedAt: string | null; }
export function TokenPanel({ initialKeys, models }: { initialKeys: Key[]; models: string[] }) {
  const [keys, setKeys] = useState(initialKeys); const [name, setName] = useState(""); const [modelsText, setModelsText] = useState(""); const [rpm, setRpm] = useState(60); const [spend, setSpend] = useState(0); const [newKey, setNewKey] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(null); const res = await fetch("/api/me/keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, allowedModels: modelsText.split(",").map((item) => item.trim()).filter(Boolean), rateLimitPerMinute: rpm, monthlySpendLimitMicros: spend }) }); const json = await res.json().catch(() => ({})); setBusy(false); if (!res.ok) return setError(json.error ?? "创建失败"); setNewKey(json.key); setKeys((prev) => [{ ...json.record, rateLimitPerMinute: rpm, monthlySpendLimitMicros: spend, monthlySpendUsedMicros: 0, lastUsedAt: null }, ...prev]); setName(""); setModelsText(""); }
  async function revoke(id: string) { const res = await fetch(`/api/me/keys/${id}`, { method: "DELETE" }); if (res.ok) setKeys((prev) => prev.map((key) => key._id === id ? { ...key, status: "revoked" } : key)); }
  return <section className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr]"><div className="flex flex-col gap-4"><h2 className="headline text-xl">我的 Token</h2>{keys.length ? <ul className="divide-y divide-line border-y border-line">{keys.map((key) => <li key={key._id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-semibold">{key.name} <span className="font-mono text-xs text-muted">{key.prefix}...</span></p><p className="font-mono text-xs text-muted">{key.rateLimitPerMinute}/min {key.lastUsedAt ? `· 最近 ${new Date(key.lastUsedAt).toLocaleDateString("zh-CN")}` : "· 未使用"}</p></div>{key.status === "active" ? <button onClick={() => revoke(key._id)} className="font-mono text-xs text-red-700 underline">吊销</button> : <span className="font-mono text-xs text-muted">已吊销</span>}</li>)}</ul> : <p className="text-sm text-muted">创建一个 Token 后即可通过 API 调用模型。</p>}</div><div className="border border-line bg-surface p-5"><h2 className="headline text-lg">创建 Token</h2><form onSubmit={create} className="mt-4 flex flex-col gap-3"><input required value={name} onChange={(event) => setName(event.target.value)} className="border border-line bg-paper px-3 py-2" placeholder="例如：本地开发" /><input value={modelsText} onChange={(event) => setModelsText(event.target.value)} className="border border-line bg-paper px-3 py-2 font-mono text-xs" placeholder="允许模型，逗号分隔（空=全部）" /><div className="grid grid-cols-2 gap-3"><input type="number" min="1" value={rpm} onChange={(event) => setRpm(Number(event.target.value))} className="border border-line bg-paper px-3 py-2" title="每分钟请求数" /><input type="number" min="0" value={spend} onChange={(event) => setSpend(Number(event.target.value))} className="border border-line bg-paper px-3 py-2" title="月消费上限（微美元，0=不限）" /></div><button disabled={busy} className="btn-primary self-start disabled:opacity-50">{busy ? "创建中" : "创建"}</button></form>{models.length ? <p className="mt-4 font-mono text-xs text-muted">可用模型：{models.join(" · ")}</p> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}{newKey ? <div className="mt-4 border border-accent p-3"><p className="eyebrow">只显示一次</p><code className="mt-1 block break-all font-mono text-xs text-accent-readable">{newKey}</code></div> : null}</div></section>;
}
